### ISSUE TITLE
Chybějící parameters v config.json

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/php-component#26]
`ConfigDefinition.php::getParametersDefinition`

```
        $parametersNode = parent::getParametersDefinition();
        // @formatter:off
        /** @noinspection NullPointerExceptionInspection */
        $parametersNode
            ->children()
                ->scalarNode('mask')
                    ->isRequired()
                ->end()
            ->end()
        ;
        // @formatter:on
        return $parametersNode;
```

### Prázdný config.json

`config.json`
```
{
}
```

=> Appka proběhne

### Prázdné paramters v config.json

`config.json`
```
{
  "parameters": {}
}
```

Appka hodí error

---

Čekal bych, že to hodí error pokaždý.

**Comment by tomasfejfar** [comment]
Imho bys musel na tom parameters node zavolat `isRequired` nejdřív. Jinak je nepovinný ;)

**Comment by ondrejhlavacek** [comment]
I see! A co bys doporučil? Mám tam poslat `isRequired()`, když pouštění bez parametrů nemá význam?

**Comment by tomasfejfar** [comment]
Jo, tak bych to udělal.

**Comment by ondrejhlavacek** [comment]
Super! Funguje to, díky.
