### ISSUE TITLE
add logger to example app?

### ISSUE THREAD

**Issue by pivnicek** [keboola/php-component#27]
Could be helpful to discourage outputting stack traces to stdout maybe:
https://github.com/keboola/php-component/blob/master/example/run.php#L15

**Comment by tomasfejfar** [comment]
Thanks! I'll need to examine the logger and how it works. Having the logger in BaseComponent would be helpful anyway.

**Comment by odinuv** [comment]
related https://github.com/keboola/component-generator/issues/44

**Comment by odinuv** [comment]
actual fix https://github.com/keboola/docker-bundle/pull/293

**Comment by odinuv** [comment]
solved by 0ad130af164510b44b8b944cda545e4db64dc304
