### ISSUE TITLE
uaaa, getLogger is missing

### ISSUE THREAD

**Issue by odinuv** [keboola/php-component#34]

**Comment by Halama** [comment]
a je to k něčemu potřeba?

**Comment by odinuv** [comment]
jenom k tomu, aby se v komponent dalo neco logovat :)

**Comment by Halama** [comment]
vždyt ho tam dostaneš v konstruktoru

**Comment by Halama** [comment]
jo už to vidím :)

**Comment by odinuv** [comment]
ale je private

**Comment by Halama** [comment]
jj, zajímavý měl jsem pocit že jsem viděl example kde byl použitý  v podeděné class, to jsem si ale asi spletl s tímhle https://github.com/keboola/php-component/pull/30/files#diff-f0cea6f799eee52b28747acbda7cb2ecR87

**Comment by tomasfejfar** [comment]
Jejda, jasně! Sorry, to mě nenapadlo otestovat. Díky 👍
