### ISSUE TITLE
No manifest should behave like empty manifest

### ISSUE THREAD

**Issue by odinuv** [keboola/php-component#35]
ErrorException : file_get_contents(C:\Users\Odin\AppData\Local\Temp/wr-storage/run-5afc5eca2e0003.61380871/in/tables/some-table-1.manifest): failed to open stream: No such file or directory
 D:\Dropbox\wwwroot\wr-storage\vendor\keboola\php-component\src\Manifest\ManifestManager.php:97

**Comment by tomasfejfar** [comment]
Fakt myslíš, že je to bug? Souhlasím, že by to mělo kontrolovat, že ten soubor existuje, ale nejsem si úplně jistý, že chceš, aby to potichu ignorovalo, že neexistuje. Mohly by z toho být těžko odhalitelné bugy. Např. když se upíšeš v názvu manifestu, tak chceš, aby ti to řeklo a ne aby to tiše "jakože načetlo", ne?

**Comment by odinuv** [comment]
hmm, no trosku jsi me nalomil, ale manifest je vec v zasade nepovinna - my ji generujeme vzdycky, ale kdyz tam neni, tak to nemusi byt chyba. Myslim, ze to, ze se prepises v nazvu manifestu by ti meli odhalit testy komponenty

**Comment by tomasfejfar** [comment]
Co kdyby to načetlo jako empty array, ale vypsalo warning/notice do logu?

**Comment by odinuv** [comment]
ja, fakt nevim no,  @ondrejhlavacek  ?

**Comment by ondrejhlavacek** [comment]
Pokud se upises v názvu manifestu, tak by to mělo zařvat, že neexistuje datovej soubor.

**Comment by tomasfejfar** [comment]
Takže podle tebe by načítání manifestu mělo kontrolovat, jestli existuje datový soubor k tomu manifestu a pokud ne, tak failnout? 

Takhle? 
```php
$manifestWithTypo = 'fileanme1';
file_exists($manifestWithTypo); //false
file_exists($manifestWithTypo . '.manifest'); // false
getManifest() // Exception('Data file "fileanme1" for manifest does not exists');
$manifestMissing = 'filename1';
file_exists($manifestMissing); // true
file_exists($manifestMissing. '.manifest'); // false
getManifest() // []
```

**Comment by ondrejhlavacek** [comment]
jj, přesně, mělo by se to chovat konzistentně s output mappingem

https://github.com/keboola/output-mapping/blob/15c227217e0e9eebf875620c65a7b4f2a580d650/Writer/Writer.php#L243-L247

**Comment by odinuv** [comment]
no to je zbytecny delat tuhle kontrolu v php-component ne? od toho to zachytava docker runner

**Comment by ondrejhlavacek** [comment]
jo, pravda, nějak jsem se vytrhl z kontextu

**Comment by tomasfejfar** [comment]
Tak to jste mi moc nepomohli :) Ať se někam posuneme, tak to pojďme zvotovat:

**Načtení neexistujícího manifestu by mělo**
👍 vrátit `[]`
👎 vyhodit exception
😕 vrátit `[]` a do logu poslat notice

**Comment by ondrejhlavacek** [comment]
Manifest není povinnej, takže notice není imho potřeba vyhazovat.
