### ISSUE TITLE
Config keys normalization

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/php-component#40]
`Config` překládá pomlčky v klíčích u `arrayNode`s na podtržítka, což je třeba explicitně vypnout pomocí `normalizeKeys(false)` v definici u komponenty. Zřejmě je to bug, resp. nežádoucí chování a mělo by se to vypnout plošně tady.

**Comment by tomasfejfar** [comment]
Necháme tak jak je, protože to zatím nejde vypnout globálně. [Pokud to projde v Symfony](https://github.com/symfony/symfony/issues/28439), tak to uděláme (pokud vás to zajímá, tak se subscribněte).
