### ISSUE TITLE
Add support for state file

### ISSUE THREAD

**Issue by Actimel** [keboola/php-component#47]
Comes up from https://github.com/keboola/db-extractor-mysql/pull/81#discussion_r223825923

Would be nice to have getter for state file. Besides there could be also method for writing into outcomes state.

**Comment by tomasfejfar** [comment]
Už tam byla issue https://github.com/keboola/php-component/issues/46 ;)

**Comment by Actimel** [comment]
👍  Nechapu jak jsem to mohl prehlednout, kdyz ty issue jsou jen 3.
