### ISSUE TITLE
more options in write table manifest

### ISSUE THREAD

**Issue by odinuv** [keboola/php-component#5]
https://keboola.slack.com/archives/C0377LNRH/p1519826779000115

https://developers.keboola.com/extend/common-interface/manifest-files/#dataouttables-manifests

https://developers.keboola.com/extend/common-interface/manifest-files/#dataoutfiles-manifests

**Comment by tomasfejfar** [comment]
Co [S3 pro soubory](https://developers.keboola.com/extend/common-interface/manifest-files/#s3-section)? Taky?

**Comment by ondrejhlavacek** [comment]
to je pro input mapping, takže ne. přijde mi, že to má nějakej blbej nadpis.
