### ISSUE TITLE
Add functional testing scaffolding

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/php-component#6]
Ref. https://github.com/keboola/processor-flatten-folders/pull/1#issuecomment-369289464

**Comment by odinuv** [comment]
podle me to patri spis do component-generator, co je tehle knihovne po tom jak testujes svoji aplikaci?

**Comment by tomasfejfar** [comment]
Měla by to být nějaká knihovna, které jen předhodíš složku s předpřipravenejma datadirama a soubor, co má spustit a ona ti to proiteruje a otestuje, že výsledek odpovídá. Teď je to na každém projektu sólo. Použít by se pak mohla klidně v rámci component-generatoru. Já bych klidně byl pro to to oddělit. Mám rád, když jsou nástoje jednoúčelové. A i když tady by to být mohlo, tak ideálně, když to bude samostatně.

**Comment by tomasfejfar** [comment]
Aha, koukám, že tam jsem kývnul na to, že to má jít sem :) To jsem asi byl nějakej unavenej :D Každopádně nemyslím si, že to patří ani sem, ani do component generatoru.

**Comment by odinuv** [comment]
souhlas :) melo by to byt uplne separatni
